-- +goose Up
CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  is_done BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS todos;
